#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          nxtA,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          nxtB,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          nxtC,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     DriveA,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     DriveB,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     LiftA,         tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     LiftB,         tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C3_1,    LifterServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//int J1_X1;
//int J1_Y1;

//TJoystick joystick;
void initializeRobot()
{
	eraseDisplay();
	nxtDisplayString(1, "Robot Initialized");
  servo[LifterServo] = 255; // Ball blocker opened
}

task main()
{
	disableDiagnosticsDisplay();
	int mThreshold = 10;
	//int SpinThreshold = 25;
	initializeRobot();
	wait1Msec(1);
	eraseDisplay();
  while (true)
  {
		getJoystickSettings(joystick);
		/*
	  if (abs (joystick.joy1_y1) > mThreshold)
	  {
		  getJoystickSettings(joystick);
		  motor[DriveA] = joystick.joy1_y1 + joystick.joy1_x1;
		  motor[DriveB] = joystick.joy1_y1 - joystick.joy1_x1;
		  nxtDisplayString(2, "Joy1 Y1 > threshold");
	  }
	  else
		{
			motor[DriveA] = 0;
		  motor[DriveB] = 0;
		  nxtDisplayString(2, "Joy1 Y1 < threshold = 10");
		}
		if (abs (joystick.joy1_y2) > SpinThreshold)
	  {
		  getJoystickSettings(joystick);
		  motor[DriveA] = joystick.joy1_y2 ;
		  motor[DriveB] = joystick.joy1_y2 * -1;
		  nxtDisplayString(3, "Joy1 Y2 > Spin");
	  }
	  else
		{
			motor[DriveA] = 0;
		  motor[DriveB] = 0;
		  nxtDisplayString(3, "Joy1 Y2 < Spin");
		}
		*/
		if ( abs(joystick.joy1_y1) > mThreshold)
		{
			motor[DriveA] = joystick.joy1_y1;
		}
		else
		{
			motor[DriveA] = 0;
		}

		if ( abs(joystick.joy1_y2) > mThreshold)
		{
			motor[DriveB] = joystick.joy1_y2;
		}
		else
		{
			motor[DriveB] = 0;
		}

		//For the movement of the ScissorLift Lifting motor: LiftA ----- *SINGLE MOTOR*
		/*
		if (joy2_TopHat == 0)
		{
			motor[LiftA] = 100;
			nxtDisplayString(4, "POV UP");
		}
		else if (joy2_TopHat == 4)
		{
			motor[LiftA] = -100;
			nxtDisplayString(4, "POV DOWN");
		}
		else
		{
			motor[LiftA] = 0;
		}
		*/
  }
}
