#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorTouch)
#pragma config(Sensor, S3,     ,               sensorTouch)
#pragma config(Sensor, S4,     ,               sensorSONAR)
#pragma config(Motor,  motorA,          nxtA,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          nxtB,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          nxtC,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     driveA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveB,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//int J1_X1;
//int J1_Y1;

//TJoystick joystick;

task main()
{
  while (true)
  {
	getJoystickSettings(joystick);
	if (abs (joystick.joy1_y1) > 10)
		{
			getJoystickSettings(joystick);
			motor[nxtA] = joystick.joy1_y1 + joystick.joy1_x1;
			motor[nxtB] = joystick.joy1_y1 - joystick.joy1_x1;
	}
	else
		{
			motor[nxtA] = 0;
		 	motor[nxtB] = 0;
		}

	if (abs (joystick.joy1_y2) > 10)
		{
			getJoystickSettings(joystick);
		  	motor[nxtA] = joystick.joy1_y2 ;
		  	motor[nxtB] = joystick.joy1_y2 * -1;
	  	}
	else
		{
			motor[nxtA] = 0;
			motor[nxtB] = 0;
		}
  }
}
