#pragma config(Hubs,	S1, HTMotor,	HTMotor,	HTServo,	none)
#pragma config(Sensor, S1,		 ,							 sensorI2CMuxController)
#pragma config(Sensor, S2,		 TouchSensorMin, sensorTouch)
#pragma config(Sensor, S3,		 TouchSensorMax, sensorTouch)
#pragma config(Motor,	 motorA,					nxtA,					 tmotorNXT, PIDControl, encoder)
#pragma config(Motor,	 motorB,					nxtB,					 tmotorNXT, PIDControl, encoder)
#pragma config(Motor,	 motorC,					nxtC,					 tmotorNXT, PIDControl, encoder)
#pragma config(Motor,	 mtr_S1_C1_1,			LiftA,				 tmotorTetrix, PIDControl)
#pragma config(Motor,	 mtr_S1_C1_2,			DriveB,				 tmotorTetrix, PIDControl)
#pragma config(Motor,	 mtr_S1_C2_1,			DriveA,				 tmotorTetrix, PIDControl)
#pragma config(Servo,	 srvo_S1_C3_1,		LifterServo,					tServoStandard)
#pragma config(Servo,	 srvo_S1_C3_2,		servo2,								tServoNone)
#pragma config(Servo,	 srvo_S1_C3_3,		servo3,								tServoNone)
#pragma config(Servo,	 srvo_S1_C3_4,		servo4,								tServoNone)
#pragma config(Servo,	 srvo_S1_C3_5,		servo5,								tServoNone)
#pragma config(Servo,	 srvo_S1_C3_6,		servo6,								tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

#include "JoystickDriver.c"
//int J1_X1;
//int J1_Y1;

//TJoystick joystick;
void initializeRobot()
{
	eraseDisplay();
	nxtDisplayString(1, "Robot Initialized");
	servo[LifterServo] = 255; // Ball blocker closed
	motor[nxtA] = 0;
	motor[nxtB] = 0;
	motor[nxtC] = 0;
	motor[DriveA] = 0;
	motor[DriveB] = 0;
	motor[LiftA] = 0;
	motor[LiftA] = 0;

	//waitforstart()

}

task main()
{
	disableDiagnosticsDisplay();
	int mThreshold = 10;
	//int SpinThreshold = 25;
	initializeRobot();
	wait1Msec(1);
	eraseDisplay();
	while (true)
	{
		getJoystickSettings(joystick);
		//bool NXT_MotorMovement;
		/*if (joy2Btn(3))
		{
		NXT_MotorMovement = true;
		}
		else
		{
		NXT_MotorMovement = false;
		}*/
		/*
		if (abs (joystick.joy1_y1) > mThreshold)
		{
		getJoystickSettings(joystick);
		motor[DriveA] = joystick.joy1_y1 + joystick.joy1_x1;
		motor[DriveB] = joystick.joy1_y1 - joystick.joy1_x1;
		nxtDisplayString(2, "Joy1 Y1 > threshold");
		}
		else
		{
		motor[DriveA] = 0;
		motor[DriveB] = 0;
		nxtDisplayString(2, "Joy1 Y1 < threshold = 10");
		}
		if (abs (joystick.joy1_y2) > SpinThreshold)
		{
		getJoystickSettings(joystick);
		motor[DriveA] = joystick.joy1_y2 ;
		motor[DriveB] = joystick.joy1_y2 * -1;
		nxtDisplayString(3, "Joy1 Y2 > Spin");
		}
		else
		{
		motor[DriveA] = 0;
		motor[DriveB] = 0;
		nxtDisplayString(3, "Joy1 Y2 < Spin");
		}
		*/
		if ( abs(joystick.joy1_y1) > mThreshold)
		{
			motor[DriveA] = -1*(100*(joystick.joy1_y1)/128);
			nxtDisplayString(2, "J1Y1>Threshold");
		}
		else
		{
			motor[DriveA] = 0;
			nxtDisplayString(2, "J1Y1<Threshold");
		}

		if ( abs(joystick.joy1_y2) > mThreshold)
		{
			motor[DriveB] = 1*(100*(joystick.joy1_y2)/128);
			nxtDisplayString(3, "J1Y2>Threshold");
		}
		else
		{
			motor[DriveB] = 0;
			nxtDisplayString(3, "J1Y2<Threshold");
		}

		//For the movement of the servo

		if (joy2Btn(1))
		{
			servo[LifterServo] = 200;
			nxtDisplayString(4, "Joy2B1 ServoOpen");
		}
		else if (joy2Btn(4))
		{
			servo[LifterServo] = 245;
			nxtDisplayString(4, "Servo Closed");
		}
		//For the movement of the ScissorLift Lifting motor: LiftA ----- *SINGLE MOTOR*
		if (joystick.joy2_TopHat == 2)
		{
			motor[LiftA] = 10;
			nxtDisplayString(5, "POV UP	 ");
		}
		else if (joystick.joy2_TopHat == 6)
		{
			motor[LiftA] = -5;
			nxtDisplayString(5, "POV DOWN");
		}
		else
		{
			motor[LiftA] = 0;
		}
		/*
		if (abs(joystick.joy2_y2) > 0)
		{
			motor[LiftA] = joystick.joy2_y2;
		}
		else
		{
			motor[LiftA] = 0;
		}*/

		//Movement of the Ball-Picking Motors, nxtA and nxtB
		if (joy2Btn(5))
		{
			motor[nxtA] = 55;
			motor[nxtB] = 55;
			nxtDisplayString(6, "NXT Motors ON ");
		}

		if (joy2Btn(6))
		{
			motor[nxtA] = 0;
			motor[nxtB] = 0;
			nxtDisplayString(6, "NXT Motors OFF");
		}
		if (joy2Btn(3))
		{
			motor[nxtA]-=20;
			motor[nxtB]-=20;
		}

	}
}
